name       : kpmcore
version    : 21.08.1
release    : 20
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/kpmcore-21.08.1.tar.xz : 342dd3ff19ceff82a90691a4f6c1e92e34bdb299048d8c616da1be094e0f82ab
license    : GPL-3.0-or-later
component  : programming.library
summary    : Library for managing partitions
description: |
    Common code for KDE Partition Manager and other projects. Library for managing partitions.
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(polkit-qt5-1)
    - pkgconfig(qca2-qt5)
    - kauth-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
