name       : kpmcore
version    : 21.04.2
release    : 16
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.2/src/kpmcore-21.04.2.tar.xz : bb5d0234ba3afd126d8142a960c53d95ca05198424441b3e0471f3794bb7e90e
license    : GPL-3.0-or-later
component  : programming.library
summary    : Library for managing partitions
description: |
    Common code for KDE Partition Manager and other projects. Library for managing partitions.
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(polkit-qt5-1)
    - pkgconfig(qca2-qt5)
    - kauth-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
