name       : kpmcore
version    : 22.04.0
release    : 26
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/kpmcore-22.04.0.tar.xz : b0ef165092fad3bd87d6084c65dee3d3134cc049f86c91793d73217c46f68dbb
license    : GPL-3.0-or-later
component  : programming.library
summary    : Library for managing partitions
description: |
    Common code for KDE Partition Manager and other projects. Library for managing partitions.
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(polkit-qt5-1)
    - pkgconfig(qca2-qt5)
    - kauth-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
