name       : kpmcore
version    : 3.2.0
release    : 2
source     :
    - https://download.kde.org/stable/kpmcore/3.2.0/src/kpmcore-3.2.0.tar.xz : 2b38c2bbc3d9a47cd4bfa2e8d2ad1bd7d791383dfe479506456b52a99ff899cb
license    : GPL-3.0
component  : programming.library
summary    : Library for managing partitions
description: |
    Common code for KDE Partition Manager and other projects. Library for managing partitions.
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(gl)
    - pkgconfig(libatasmart)
    - pkgconfig(libparted)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kservice-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
