name       : kpmcore
version    : 21.12.1
release    : 24
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/kpmcore-21.12.1.tar.xz : 777e8c584933218b928c8c0a00f49d31f5b9719557174f4f4271d1b6ca08739a
license    : GPL-3.0-or-later
component  : programming.library
summary    : Library for managing partitions
description: |
    Common code for KDE Partition Manager and other projects. Library for managing partitions.
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(polkit-qt5-1)
    - pkgconfig(qca2-qt5)
    - kauth-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
