name       : kpmcore
version    : 23.04.3
release    : 35
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/kpmcore-23.04.3.tar.xz : 89068cbec609a2ed2e48ec609dfe35eff4f3cb39456c84e7a647754dd0bfe033
license    : GPL-3.0-or-later
component  : programming.library
summary    : Library for managing partitions
description: |
    Common code for KDE Partition Manager and other projects. Library for managing partitions.
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(polkit-qt5-1)
    - pkgconfig(qca2-qt5)
    - kauth-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
